// Generated by CoffeeScript 1.8.0
(function() {
  var getFormated, getSign;

  $(function() {
    var c, ctx, devicemotionHandler, draw, h, max, update, w, x, y, z;
    c = document.getElementById("main_canvas");
    ctx = c.getContext("2d");
    w = c.width = $(window).width();
    h = c.height = $(window).width();
    x = 0;
    y = 0;
    z = 0;
    max = 10;
    update = function() {};
    draw = function() {
      ctx.clearRect(0, 0, w, h);
      ctx.lineWidth = 2;
      ctx.strokeStyle = "#FF0000";
      ctx.fillStyle = "#FF0000";
      ctx.beginPath();
      ctx.moveTo(w / 2, h / 2);
      ctx.lineTo(w / 2 + x / max * w / 2, h / 2 + y / max * h / 2);
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(w / 2 + x / max * w / 2, h / 2 + y / max * h / 2, 8, 0, 2 * Math.PI, false);
      return ctx.fill();
    };
    setInterval(function() {
      update();
      return draw();
    }, 33);
    devicemotionHandler = function(event) {
      x = event.acceleration.x;
      y = event.acceleration.y;
      return z = event.acceleration.z;
    };
    return window.addEventListener("devicemotion", devicemotionHandler);
  });

  getSign = function(n) {
    if (n >= 0) {
      return "+";
    } else {
      return "-";
    }
  };

  getFormated = function(n) {
    var num;
    num = Math.floor(Math.abs(n) * 100) / 100;
    return num.toString();
  };

}).call(this);
